name: movement_clean
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - scipy
  - numpy
  - matplotlib
  - pandas
  - geopandas
  - numba
  - rasterio
  - jupyter
  - ipython
  - seaborn

